export const INDUSTRY_OPTIONS = [
    { value: 'Retail', label: 'Retail' },
    { value: 'E-Commerce', label: 'E-Commerce' },
    { value: 'Service', label: 'Service Business' },
    { value: 'Tech', label: 'Technology & SaaS' },
    { value: 'Food', label: 'Food & Beverage' },
    { value: 'Health', label: 'Health & Wellness' },
    { value: 'Beauty', label: 'Beauty & Cosmetics' },
    { value: 'Real Estate', label: 'Real Estate' },
    { value: 'Education', label: 'Education & Training' },
    { value: 'Finance', label: 'Finance & Insurance' },
    { value: 'Legal', label: 'Legal Services' },
    { value: 'Construction', label: 'Construction & Trades' },
    { value: 'Automotive', label: 'Automotive' },
    { value: 'Entertainment', label: 'Entertainment & Media' },
    { value: 'Travel', label: 'Travel & Hospitality' },
    { value: 'Marketing', label: 'Marketing & Advertising' },
    { value: 'Non-Profit', label: 'Non-Profit / Charity' },
    { value: 'Consulting', label: 'Consulting' },
    { value: 'Fashion', label: 'Fashion & Apparel' },
    { value: 'Fitness', label: 'Fitness & Sports' },
    { value: 'Art', label: 'Art & Design' },
    { value: 'Events', label: 'Events & Weddings' },
    { value: 'Photography', label: 'Photography' },
    { value: 'Agriculture', label: 'Agriculture & Farming' },
    { value: 'Manufacturing', label: 'Manufacturing' },
    { value: 'Logistics', label: 'Logistics & Transport' }
];
